#!/usr/bin/env python3
"""Build an offline HTML guide from reviewed, local JSON and configuration files."""
from pathlib import Path
from html import escape as e
import json,re
R=Path(__file__).resolve().parents[1]; G=R/'guide'
def code(s):return '<code>'+e(s)+'</code>'
def keys(s):return '<kbd>'+e(s)+'</kbd>'
def table(headers,rows):return '<div class="table-wrap"><table><thead><tr>'+''.join('<th scope="col">'+e(h)+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+v+'</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def section(id,num,title,body):return f'<section id="{id}"><div class="section-label">{num}</div><h2>{title}</h2>{body}</section>'
ray=json.loads((G/'raycast-shortcuts.json').read_text());tools=json.loads((G/'tool-inventory.json').read_text())
nav=[('raycast','Raycast & global keys'),('workflow','Everyday workflows'),('vscode','VS Code'),('shell','Terminal & Git'),('vim','Neovim & tmux'),('directory','Installed tools'),('manage','Manage this setup')]
parts=['''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nir's Mac — Tools & shortcuts</title><meta name="description" content="A local field guide to Nir's Mac: verified Raycast hotkeys, VS Code, shell commands and optional Neovim."><link rel="stylesheet" href="style.css"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' rx='8' fill='%23102a43'/%3E%3Ctext x='7' y='29' font-size='26' font-family='monospace' fill='%23ff946c'%3E%3E_%3C/text%3E%3C/svg%3E"></head><body id="top"><aside class="sidebar"><div class="brand">nir<span>.</span> / mac</div><div class="eyebrow">Personal field guide</div><nav aria-label="Guide sections">'''+''.join(f'<a href="#{id}">{title}</a>' for id,title in nav)+'''</nav><footer>Verified 26 September 2026<br>Stored with your dotfiles.<br>Find anything with ⌘ F.</footer></aside><main><header><div class="eyebrow">Your computer · Your conventions</div><h1>Tools & shortcuts.</h1><p class="intro">Open the right app, move a window, jump back to an edit. A reference for the way your Mac is configured.</p><div class="strip"><div><strong>21</strong><span>Raycast command hotkeys</span></div><div><strong>⌥ Space</strong><span>Open Raycast</span></div><div><strong>Right ⌥</strong><span>Your Hyper key</span></div></div></header>''']
body='<p>Raycast itself provides your Hyper key (Settings → Keyboard, Include Shift enabled). Hold <strong>Right Option</strong> to send Hyper: Control + Option + Shift + Command. Left Option keeps its normal behavior. These assignments were read from the current Raycast settings, including the enabled state.</p><div class="note"><strong>Read the symbols</strong><br>⌘ Command · ⌥ Option · ⌃ Control · ⇧ Shift · ⇥ Tab · ↵ Return. '+keys('⌃ ⌃')+' means a double press of Control.</div>'
for category in ['Launcher','Applications','Extensions','Window Management']:
 rows=[(e(x['command']),keys(x['keys']),code(x['alias']) if x['alias'] else '—') for x in ray['shortcuts'] if x['category']==category]
 body+='<h3>'+category+'</h3>'+table(['Action','Global shortcut','Raycast alias'],rows)
body+='<p class="muted">“ChatGPT” and “ChatGPT Classic” are the labels Raycast currently shows. The alias '+code('codex')+' belongs to ChatGPT in that list. Hyper + O opens the Ollama AI extension’s Improve Writing command. OCR and clipboard commands are global, so they can override a focused app’s Control shortcuts.</p>'
body+='<h3>Keyboard navigation outside Raycast</h3>'+table(['Tool','Shortcut','Use'],[(e('Homerow'),keys('Hyper H'),'Control app buttons and links from the keyboard: show hints, then type a hint to click.'),(e('Homerow'),keys('Hyper J'),'Start keyboard scrolling. Arrow-key scrolling is enabled.'),(e('AltTab'),keys('⌘ Tab')+' / '+keys('⌘ `'),'Window switching, as documented in your older setup notes. These AltTab bindings have not been re-verified live.')])
body+='<p><a href="raycast-shortcuts.json">Reviewed hotkey data</a> · <code>preferences/homerow.json</code> records the current Homerow mappings. These are your daily controls across supported apps: Hyper H for clicking and Hyper J for scrolling. Hyper is Right Option, provided by Raycast. The installed Homerow uses com.superultra.Homerow; an older preference file has the H/J keys reversed.</p>'
body+='<h3>Native macOS screen zoom</h3><p>Hold '+keys('Right Ctrl')+' and scroll the mouse wheel to zoom in or out. This is configured in <strong>System Settings → Accessibility → Zoom</strong>: enable “Use scroll gesture with modifier keys to zoom”, choose <strong>Control</strong>, and use <strong>Full Screen</strong> zoom. macOS selects Control without distinguishing left from right; Right Ctrl is your preferred key.</p><p>The scroll-to-zoom toggle and Control modifier values were read from this Mac on 30 September 2026 and are saved in <code>preferences/macos.json</code>. <code>./setup install</code> (unless <code>--skip-preferences</code>) or <code>./setup defaults</code> applies them with per-key backups. For the installed macos-defaults tool, preview with <code>macos-defaults --dry-run apply macos-defaults/zoom.yaml</code> and apply with <code>macos-defaults apply macos-defaults/zoom.yaml</code>; that direct tool command does not create the setup backup. Log out and back in if needed, then verify Right Ctrl + wheel and Full Screen style. <a href="https://support.apple.com/guide/mac-help/change-zoom-settings-for-accessibility-mh40579/mac">Apple’s Zoom settings reference</a>.</p>'
body+='<h3>Your local Raycast extensions</h3><p>These 75 extension packages are present on this Mac. Open Raycast and search a command title to use it; individual commands may be disabled or require an account. This list is read from extension manifests and does not include their private preferences.</p>'
for extension in json.loads((G/'raycast-extensions.json').read_text()):
    body+='<details><summary>'+e(extension['name'])+'</summary><div class="detail-body"><p>'+e(extension['description'])+'</p>'+table(['Search command','Purpose'],[(e(x['name']),e(x['description'])) for x in extension['commands']])+'</div></details>'
parts.append(section('raycast','01 / LAUNCH & MOVE','Raycast & global keys',body))
body='''<p>Start with a task, then reach for the tool you already configured.</p><div class="grid">
<article class="panel"><h3>Start coding</h3><p>Press <kbd>Hyper I</kbd> for VS Code. Use <kbd>⌘ E</kbd> to find a file, <kbd>⌘ ↑</kbd> / <kbd>⌘ ↓</kbd> to jump between code blocks, and <kbd>⇧ ⌘ Backspace</kbd> to return to the last edit.</p><p>In a terminal: <code>pp</code> → <code>j project-name</code> → <code>code .</code> → <code>prd</code>. Use <code>rs</code> when you need to choose a package script.</p></article>
<article class="panel"><h3>Put two things side by side</h3><p>Focus one window and press <kbd>⌃ ⌥ ←</kbd>. Focus the other and press <kbd>⌃ ⌥ →</kbd>. Move a window between displays with <kbd>⌃ ⌥ ⌘ ←</kbd> / <kbd>⌃ ⌥ ⌘ →</kbd>.</p><p><kbd>⌃ ⌥ Return</kbd> maximizes the current window. These are Raycast commands.</p></article>
<article class="panel"><h3>Work with text</h3><p><kbd>⌃ V</kbd> opens clipboard history. <kbd>⌃ O</kbd> recognizes text from the screen. <kbd>⌃ ⌃</kbd> looks up a word. <kbd>Hyper O</kbd> runs Improve Writing through the Ollama AI extension.</p><p>Your separate “Fix Spelling and Grammar” script reads the clipboard, calls local Ollama on port 11434 with model <code>phi3</code>, and copies the result back. It has no verified global hotkey.</p></article>
<article class="panel"><h3>Browse and capture</h3><p><kbd>Hyper B</kbd> opens Chrome; <kbd>Hyper N</kbd> opens Obsidian. Your saved Vimium convention is <kbd>f</kbd> to click a link and <kbd>⇧ F</kbd> to open it in a new tab. This comes from your setup notes, not a live browser export.</p><p>For a selected area, <kbd>⌃ ⌘ ⇧ 4</kbd> copies to the clipboard; <kbd>⌘ ⇧ 4</kbd> saves a file in <code>/tmp</code>. These are your native macOS shortcuts. Use Zappy for images, GIFs and quick videos; use QuickTime Player for better-quality video.</p></article>
</div><h3>Useful Raycast search commands</h3><p>Open Raycast with <kbd>⌥ Space</kbd>, type the command, then press Return.</p>'''
body+=table(['Search for','What to do'],[(code('projects'),'List Git repositories with your Git Repos extension.'),(code('quit'),'Quit Non-Focused from Single Focus. Save work first.'),(code('kill port'),'Find a listening port with Port Manager.'),(code('close app'),'Find a process with Kill Process; terminating it can lose unsaved work.'),(e('To Hebrew / To Latin'),'Convert keyboard-layout text with Aleph Tools.'),(e('Search Files / Search Snippets / Create Snippet'),'Find a file, insert reusable text, or save a new snippet.'),(e('Open dotfiles'),'Your script opens this repository in VS Code after its script directory is registered.'),(e('Open blog / Open eslint config / Work mode'),'Preserved personal script commands; project paths still follow your own repository locations.')])
body+='<p class="muted">Aliases above were visible in your Raycast launcher. Extension accounts, models and permissions stay in Raycast. For a new Mac, use Raycast Cloud Sync or a fresh export; the saved 2025 export is historical.</p>'
capture=json.loads((R/'preferences/capture-workflow.json').read_text())
dictation=json.loads((R/'preferences/dictation.json').read_text())
body+='<h3>Dictate text</h3>'+table(['Setting','Your workflow'],[(e('Default app'),e(dictation['app'])+' — built into macOS.'),(e('Start / stop'),keys('Right ⌘ twice')+' — '+e(dictation['shortcut'])+'.'),(e('Languages'),e(' and '.join(dictation['languages']))),(e('Microphone source'),e(dictation['microphone']))])
body+='<p>Click a text field, press Right Command twice, and speak. Type corrections while dictating; press the shortcut again or Escape to finish. Switch languages using the indicator beside the cursor. Handy and other installed dictation apps are optional alternatives.</p>'
body+='<p class="muted">Verified '+e(dictation['verified'])+' in System Settings → Keyboard → Dictation. The default install and <code>./setup defaults</code> restore enablement, languages and this shortcut while preserving other system shortcuts. You can also run <code>macos-defaults apply macos-defaults/dictation.yaml</code> (preview with <code>--dry-run</code>). On a new Mac, verify Automatic microphone selection and let macOS download speech assets. <a href="../manual-install/dictation.md">Dictation settings and restore</a> · <a href="https://support.apple.com/guide/mac-help/dictate-messages-and-documents-mh40584/mac">Apple Dictation guide</a>.</p>'
quick_app=capture['quick_gif_video']['app']
body+='<h3>Capture and record</h3>'+table(['Task','Tool or shortcut'],[(e('Selected area → clipboard'),keys('⌃ ⌘ ⇧ 4')+' — select an area, then paste where needed.'),(e('Selected area → file'),keys('⌘ ⇧ 4')+' — select an area; the current save destination is '+code(capture['save_location'])+'.'),(e('Image capture / markup'),e(capture['images'])),(e('Quick GIF or short casual recording'),e(quick_app)),(e('Better-quality video'),e(capture['better_video'])+' — your preferred recording tool.')])
body+='<p class="muted">Save location verified from this Mac; tool preferences supplied by you. Zappy is confirmed for images, GIFs and quick videos. <a href="https://support.apple.com/en-us/102646">Apple screenshot shortcuts</a>.</p>'
body+='<p>Shottr is also installed and was running when checked, but it is not part of your confirmed capture workflow. Consider removing it unless you use its scrolling captures, pixel measurements or image-cleanup tools. <a href="https://shottr.cc/">Shottr features</a>.</p>'
parts.append(section('workflow','02 / COMMON TASKS','Everyday workflows',body))
body='''<p>VS Code remains your default editor. Your Default, Home, Work and Cursor Default configurations are preserved. “Cursor Default” is a VS Code profile name, not a switch to the Cursor app.</p><p>The main coding profile uses JetBrains Mono at 16px, Webstorm Darcula, wrapped lines, and language-specific formatters. It limits each editor group to five tabs and keeps preview tabs disabled.</p>'''
labels={'git.revertSelectedRanges':'Discard selected changed lines','gotoLastEdit.goBack':'Go back to the last edit','gotoLastEdit.goForward':'Go forward through edits','editsHistory.moveCursorToNextEdit':'Next edit (Edits History extension)','workbench.action.quickOpen':'Find and open a file','block-travel.jumpUp':'Jump to previous code block','block-travel.jumpDown':'Jump to next code block','block-travel.selectUp':'Select to previous code block','block-travel.selectDown':'Select to next code block','editor.action.surroundWithSnippet':'Wrap selection with a snippet','editor.action.insertSnippet':'Insert a snippet','editor.emmet.action.removeTag':'Remove surrounding HTML tag','editor.emmet.action.matchTag':'Jump to matching HTML tag','composerMode.agent':'Cursor-specific agent command (may be unavailable in VS Code)','editor.action.dirtydiff.next':'Next changed section in the file','editor.action.dirtydiff.previous':'Previous changed section in the file','notebook.diff.action.next':'Next notebook difference','notebook.diff.action.previous':'Previous notebook difference','workbench.action.focusActiveEditorGroup':'Return focus to the editor','git.openFile':'Open source file from a diff','workbench.files.action.createFileFromExplorer':'Create a file in Explorer','git.clean':'Discard selected files’ changes','list.focusUp':'Move up in the focused list','list.focusDown':'Move down in the focused list','list.focusFirst':'First item in the focused list','list.focusLast':'Last item in the focused list','list.focusPageUp':'Page up in the focused list','list.focusPageDown':'Page down in the focused list','runCommands':'Focus search results or the Source Control file list'}
def keyfmt(s):
 for a,b in [('shift','⇧'),('ctrl','⌃'),('alt','⌥'),('cmd','⌘'),('backspace','Backspace'),('escape','Escape'),('left','←'),('right','→'),('down','↓'),('up','↑')]:s=s.replace(a,b)
 return s.replace('+',' ').replace('page↑','Page Up').replace('page↓','Page Down')
bindings=json.loads((R/'editors/vscode/profiles/Cursor Default/keybindings.json').read_text())
rows=[]
for b in bindings:
 if b['command'].startswith('-'):continue
 desc=e(labels.get(b['command'],b['command']))
 if b.get('when'):desc+='<small>'+e(b['when'])+'</small>'
 rows.append((keys(keyfmt(b['key'])),desc))
body+=table(['Shortcut','Action and context'],rows)
body+='''<div class="note warning"><strong>Git discard shortcuts change files.</strong><p><kbd>⌥ ⌘ Z</kbd> discards selected lines in a diff, or selected files in Source Control. Review the selection first. Your profile also contains both Edits History and Go to Last Edit bindings for the same forward shortcut; the active context and installed extensions determine which handles it.</p></div><h3>Restore your editor on another Mac</h3><ol class="steps"><li>Open VS Code’s Profiles menu and choose Import Profile.</li><li>Import the matching <code>.code-profile</code> file from <code>editors/vscode/</code>. It contains current settings, shortcuts, snippets and extension IDs.</li><li>Select Cursor Default for your usual coding workflow. Your live settings are untouched. Core setup leaves VS Code alone; only the optional <code>vscode</code> link profile replaces editor files. Profile IDs are resolved by name.</li></ol><p>Open Keyboard Shortcuts in VS Code to resolve an extension command that no longer exists. The imported Cursor-specific Agent key is preserved but may not do anything in VS Code.</p>'''
parts.append(section('vscode','03 / WRITE & REVIEW','VS Code',body))
body='''<p>Your shell stays on Oh My Zsh with Starship, fnm, pnpm, McFly, fzf and zoxide. Your familiar <code>j</code> now uses zoxide, with autojump history imported. Schnitz’s useful utilities live beside your own in <code>bin/</code>. Your aliases win when the names overlap.</p>'''
body+=table(['Command / key','Use'],[(code('pp'),'Go to ~/dev/work.'),(code('z name'),'Jump to a frequently used directory with zoxide.'),(code('j name'),'Your familiar shortcut, now an alias for zoxide’s z command.'),(code('ji name / zi name'),'Choose a directory interactively with fzf; useful when a query matches multiple projects.'),(code('ll'),'List files, including hidden files, Git status and icons with eza.'),(code('cat file'),'Read a syntax-highlighted file with bat.'),(code('rs'),'Choose and run a script from the current package.json.'),(code('ps'),'Choose a package script across this Git repository. This is your custom project command; use command ps for the system process listing.'),(code('prd / d'),'Run pnpm run dev.'),(code('prl / prt / prc'),'Run lint, type-check, or ci package scripts.'),(code('scripts'),'Show package.json scripts with jq.'),(code('lc'),'Choose a previous command from this directory. It is now placed on the prompt for review; press Return to run it.'),(keys('⌃ R'),'McFly history search, when installed.'),(keys('⌃ T')+' / '+keys('⌥ C'),'fzf file selection / directory selection. Terminal Option behavior can affect Alt-C.'),(keys('⌃ A')+' / '+keys('⌃ E'),'Beginning / end of command line.'),(keys('⌃ X')+' then '+keys('⌃ E'),'Edit the shell command in your default editor, VS Code.'),(code('find_port_blocker 3000'),'Show which process listens on a port.'),(code('kp'),'Terminate your configured backend ports: 8081, 8082, 8083, 8084 and 8086.'),(code('t file'),'Move a file to macOS Trash using the trash CLI.'),(code('mv file'),'Interactively rename one file; multi-argument mv asks before overwriting.'),(code('touchp path/to/file'),'Create missing parent directories, then the file.'),(code('mkcd parent/new-project'),'Create the directory and its parents, then enter it. Quote paths containing spaces. Stays put if creation fails.'),(code('hidedesktop / showdesktop'),'Hide or show desktop icons; Finder restarts.')])
body+='''<h3>Terminal choices</h3><p><strong>Warp is your daily terminal</strong> (<kbd>Hyper T</kbd>). It provides command/option/path completions and history-based autosuggestions, so the retired Fig hooks are unnecessary. <a href="https://docs.warp.dev/terminal/command-completions">Warp documentation</a>.</p><p><strong>Ghostty is the optional alternative</strong> when you want a native terminal with tabs and splits. Keep your usual shell commands; no need to adopt Schnitz’s tmux shortcuts. <a href="https://ghostty.org/docs/about">Ghostty documentation</a>.</p><p><strong>Herdr is worth evaluating for multiple agent sessions</strong>: its focus is persistent workspaces and status across agent terminals. It is not part of this setup. <a href="https://herdr.dev/">Herdr</a>.</p><p>In Warp, use <code>ji project</code> for an interactive directory picker: zoxide’s Space+Tab completion is not supported there. Both <code>j</code> and <code>z</code> work. <a href="https://github.com/ajeetdsouza/zoxide">Zoxide documentation</a>.</p>'''
body+='<h3>Your compact prompt</h3><p>Directory, Git branch and the usual Starship prompt symbol on the left; command duration on the right for longer commands. It uses Schnitz’s compact layout with Starship’s default colors and symbol. Edit <code>.config/starship.toml</code> in this repo; it is linked as <code>~/.starship.toml</code>. Warp must be displaying the shell prompt to show Starship.</p>'
body+='<h3>Your Git vocabulary</h3>'+table(['Command','Meaning'],[(code('git co'),'Commit. Schnitz’s checkout alias was not imported over this.'),(code('git ch branch'),'Check out a branch.'),(code('git cp'),'Interactively commit with patches.'),(code('gap'),'Stage selected hunks with git add -p.'),(code('gb / sb'),'List branches by activity / choose a branch with fzf.'),(code('gitroot / cdgr'),'Change directory to the repository root. The bin/gitroot executable prints the path.'),(code('gbb'),'Create a timestamped backup branch at the current commit.'),(code('git lg / git graph'),'Display graph views of Git history.'),(code('git pr NUMBER'),'Fetch a pull-request branch and check it out.'),(code('wip'),'Stage everything and make a Lumen-generated WIP commit, skipping hooks.'),(code('gcr'),'Your retained Lumen commit/revert/reset workflow. It changes history and skips hooks; read shell/functions.zsh before using.'),(code('git-force-pull / git-legacy'),'Retained advanced commands that can discard or rewrite work. Inspect their source before use.')])
body+='<h3>Useful additions from Schnitz</h3>'+table(['Command','Use / prerequisite'],[(code('dfile'),'Pick changed files with an fzf diff preview; needs Git, fzf, bat and delta.'),(code('dfile-list [ref]'),'Print changed file paths relative to the current directory; needs Node.'),(code('dls / dpick'),'List Docker containers / choose containers with an fzf log preview; Docker must be running.'),(code('brew-interactive'),'Choose outdated Homebrew formulae to upgrade. Escape cancels without upgrading.'),(code('pretty-json / jqi'),'JSON helpers; check the script for its expected input.'),(code('wait-until-passes "COMMAND"'),'Retry a command until it succeeds; use a command safe to repeat.'),(code('wtfeat NAME'),'Create a feature worktree under ~/dev/worktrees, using a new nirtamir/NAME branch. WORKTREE_ROOT and GIT_BRANCH_PREFIX customize the defaults.'),(code('schnizvim [file]'),'Open the optional Schnitz Neovim configuration without changing your default nvim setup.')])
body+='<p>Schnitz’s personal integrations, conflicting settings and bundled language-server binaries were removed from the maintained tree. Originals remain in the ignored local archive; see <code>docs/CLEANUP.md</code>.</p>'
parts.append(section('shell','04 / COMMAND LINE','Terminal & Git',body))
body='''<p>Explore these when you want to. VS Code stays the default, and your existing <code>~/.config/nvim</code> is left alone.</p><div class="grid"><article class="panel"><h3>Try Schnitz’s Neovim</h3><pre><code>./setup plan --profile vim
./setup link --profile vim
./bin/schnizvim</code></pre><p>If the plan reports an existing target, use <code>--replace</code> only after reviewing it. The first launch downloads plugins via lazy.nvim; language tools may require additional installation or accounts.</p><p>Press <kbd>i</kbd> to insert, <kbd>Escape</kbd> for normal mode, then <code>:w</code> to save, <code>:q</code> to quit, or <code>:q!</code> to abandon unsaved changes.</p></article><article class="panel"><h3>Try tmux</h3><pre><code>./setup link --profile tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
tmux</code></pre><p>Clone TPM only if that directory does not already exist. Inside tmux press <kbd>⌃ S</kbd>, then <kbd>⇧ I</kbd> to install plugins. This profile uses Control-S as its prefix.</p><p>Warp is your primary terminal. Ghostty is an optional alternative; its bindings are not replaced with Schnitz’s tmux-dependent setup.</p></article></div>'''
body+=table(['Neovim key (normal mode unless noted)','Action'],[(keys('Ctrl P'),'Find a file.'),(keys('Tab')+' or '+keys(', Tab'),'List open buffers.'),(keys(', e')+' / '+keys(', w'),'Next / previous buffer.'),(keys('Backspace'),'Switch to the alternate buffer.'),(keys(';'),'Enter command mode, like colon.'),(keys('Y'),'Yank from the cursor to the end of the line.'),(keys(', q')+' or '+keys('Return'),'Clear search highlighting.'),(keys(', f'),'Toggle a fold.'),(keys(', di'),'Show diagnostics at the cursor.'),(keys(', L'),'List diagnostics.'),(keys(', od'),'Find changed files with a diff preview.'),(keys(', dd'),'Close a buffer; ,DD forces closure and can lose edits.'),(keys(', yr')+' in visual mode','Copy the relative path and selected line range.'),(keys('Ctrl C')+' in insert mode','Return to normal mode.')])
body+='<p>The leader key is <kbd>,</kbd> and local leader is <kbd>\\</kbd>. Plugin shortcuts require the plugin installation to finish.</p>'
body+=table(['tmux keys','Action'],[(keys('Ctrl S')+' then '+keys('c'),'New window in the same directory.'),(keys('Ctrl S')+' then '+keys('%'),'Split left/right.'),(keys('Ctrl S')+' then '+keys('"'),'Split top/bottom.'),(keys('Alt h / j / k / l'),'Move between panes.'),(keys('Alt b / n'),'Previous / next window.'),(keys('Alt w'),'Close a pane (and its running process).'),(keys('Alt ;'),'Toggle pane zoom.'),(keys('Ctrl S')+' then '+keys('d'),'Detach; reattach with tmux attach.'),(keys('Ctrl S')+' then '+keys('r'),'Reload the tmux configuration.')])
body+='<p class="muted">Raycast’s global Control-F can intercept a tmux or shell binding before the terminal receives it. If a shortcut behaves unexpectedly, check the global table first.</p>'
parts.append(section('vim','05 / OPTIONAL WORKFLOWS','Neovim & tmux',body))
body='<p>This is a snapshot of packages installed through Homebrew on 26 September 2026. “Installed” does not imply daily use. Package descriptions come from Homebrew metadata; the full list also includes libraries pulled in as dependencies.</p>'
for kind,title,predicate in [('cask','Desktop apps',lambda x:x['kind']=='cask'),('brew','Command-line tools',lambda x:x['kind']=='brew' and x['direct']),('deps','Supporting libraries & packages',lambda x:x['kind']=='brew' and not x['direct'])]:
 group=sorted([x for x in tools if predicate(x)],key=lambda x:x['name'].lower())
 rows=[]
 for x in group:
  name=e(x['name']);url=x.get('homepage') or ''
  if url.startswith(('https://','http://')):name='<a href="'+e(url,quote=True)+'" target="_blank" rel="noreferrer">'+name+'</a>'
  rows.append((name,e(x['description'])))
 content=table(['Tool','Purpose'],rows)
 if kind=='deps':body+='<details><summary>'+title+f' ({len(group)})</summary><div class="detail-body">'+content+'</div></details>'
 else:body+='<h3>'+title+f' <span class="badge">{len(group)}</span></h3>'+content
body+='<details><summary>Applications found outside the package inventory (full app list)</summary><div class="detail-body"><p>All 123 app bundles found directly in /Applications and ~/Applications. This includes apps installed manually. Package descriptions above cover apps known to Homebrew; no usage frequency is inferred.</p>'+table(['Application','Installed version'],[(e(x['name']),e(x['version']) or '—') for x in json.loads((G/'applications.json').read_text())])+'</div></details>'
body+='<h3>Other tools in your setup notes</h3><p>Homerow, BetterDisplay, Script Kit, Syncthing, Open WebUI, Pinokio and other manual installs are documented under <code>manual-install/</code>. Those notes are preserved historical instructions; availability, pricing and hotkeys may have changed.</p>'
body+='<h3>Install declarations needing attention</h3><p>Some older names are unavailable or disabled in the current Homebrew catalog. Their entries remain documented, but the installer skips them; existing apps were not uninstalled.</p>'
review=json.loads((R/'packages/availability-review.json').read_text())
body+=table(['Tool','Why it needs a manual restore'],[(code(x['name']),e(x['reason'])) for x in review])
body+='<p>Fig and iTerm are retired from the managed setup. Authy, Android File Transfer, Rewind and docker-machine remain in the legacy review list. Third-party taps have not been tested by installing them.</p><p><a href="tool-inventory.json">Download the installed-tool inventory</a> · <a href="https://formulae.brew.sh/">Homebrew package catalog</a></p>'
parts.append(section('directory','06 / REFERENCE','Installed tools',body))
body='''<p>For a new Mac, copy this working checkout to a permanent folder, then run <code>./setup install</code>. Preview with <code>./setup install --dry-run</code>. Core, daily apps and the full extras list are included; <code>--minimal</code> skips extras. Existing VS Code and Warp files are preserved. The script saves a log and a checklist for account logins, keys and macOS permissions. Run <code>./setup doctor</code> to review remaining gaps. Read <code>docs/NEW-MAC.md</code> and <code>docs/MACHINE-AUDIT.md</code> for details.</p><p>The repository is the source of truth. Change a file here, then preview or apply the part you need.</p><pre><code>./setup plan                   # inspect the core links
./setup link --replace         # back up conflicts and link
./setup status                 # inspect link status
./setup packages               # report missing core packages
./setup packages core --apply  # install missing core packages
./setup shell                  # install missing shell plugins
./setup guide                  # open this local page</code></pre><p>Link backups go to <code>~/.local/state/dotfiles/backups/</code>. Each run prints an exact <code>./setup restore .../manifest.json</code> command. Restore refuses to overwrite files you changed after linking.</p>'''
body+=table(['Location','Edit here'],[(code('Brewfile / packages/'),'Core tools, extra apps, work apps, App Store apps, Node CLIs and a machine inventory.'),(code('shell/ / .zshrc'),'Your aliases, functions and shell startup.'),(code('.config/starship.toml'),'Compact prompt layout, linked as ~/.starship.toml.'),(code('bin/'),'Your executable helpers plus portable Schnitz scripts.'),(code('editors/vscode/'),'Default settings and portable Home, Work and Cursor Default profiles.'),(code('.config/schnizvim/ / .config/tmux/'),'Optional editor and terminal multiplexer configuration.'),(code('preferences/raycast-keyboard.json'),'Verified Raycast-native Hyper mapping; no Karabiner required.'),(code('raycast/'),'Your script commands and my-stuff extension source.'),(code('preferences/macos.json / preferences/desktop/'),'Active macOS and desktop restore settings. Historical YAML remains under macos-defaults/.'),(code('.private/'),'Ignored source archive and private exports; not portable through Git.'),(code('guide/'),'This offline guide and its reviewed shortcut/inventory data.')])
body+='''<h3>Raycast on a new Mac</h3><ol class="steps"><li>Install Raycast. Restore Raycast with Cloud Sync or a fresh settings export; the historical export is kept privately.</li><li>In Raycast Settings → Keyboard, set Hyper Key to Right Option and enable Include Shift.</li><li>Register this repo’s <code>raycast/scripts/quick open</code> and <code>raycast/scripts/custom</code> folders in Raycast Script Commands. Build <code>raycast/my-stuff</code> separately if you use that extension.</li><li>Set the launcher to <kbd>⌥ Space</kbd> and check every shortcut in the table against the restored settings.</li><li>Grant Accessibility permissions in macOS when the apps request them. Reconnect extension accounts inside Raycast.</li></ol><h3>What is deliberately separate</h3><p>Package installation, Mac preferences, keyboard mappings, Node tools, and optional editor setup each have their own command. Running <code>./setup</code> alone only shows help. No setup step resets Raycast, installs a different window manager, removes existing packages, or runs your old destructive installer.</p><p>Your original <code>~/dotfiles</code> remains in place. Its keyboard instructions now describe Raycast native Hyper; both repos and your live shell use zoxide-backed <code>j</code>, with Fig/iTerm startup hooks removed. Open a new Warp tab to use the updated shell. The local archive preserves authored source files; dependency folders, editor history, session databases and Git metadata were excluded. Secrets and old Raycast exports stay out of version control.</p><p>Read <code>README.md</code> and <code>docs/MIGRATION.md</code> for the complete migration decisions. To update this page after editing the reviewed data, run <code>python3 guide/build.py</code>.</p>'''
parts.append(section('manage','07 / KEEP IT YOURS','Manage this setup',body))

parts.append('<footer><a class="top-link" href="#top">Back to top ↑</a><p>Local reference. No analytics, remote assets, account data, or clipboard history.</p></footer></main></body></html>')
(G/'index.html').write_text(''.join(parts))
print('Built',G/'index.html')
